### ISSUE TITLE
Do you plan to maintain nixos-config in literate org-mode?

### ISSUE THREAD

**Issue by idlip** [novoid/nixos-config#7]
Hi novoid, I was recently reading some of your articles on PIM and a talk about local file management, and got fascinated about them.

So I wondered why not maintain nixos-config in org file too.
Actually its possible, I have used it before, but I switched to modular config (both emacs and nixos) thinking, that is what world demands to work with lots of file tree.

Am on edge right now, thinking to switch back to maintaining single org file for nixos-config and emacs.

So, have you planned or any thoughts on maintaining nixos-config in org file too?

I'm no expert in both the domains, just wanting to know your opinion.

**Comment by novoid** [comment]
Hi @idlip ,

I was thinking about that as well for a couple of minutes.

However, I don't see the big benefit for me at the moment. With my Emacs configuration, I'm adding many URLs, comments, links, ... to the configuration.

With NixOS, I currently don't need more than a one-line comment for a section or entry. At the moment, any convertion effort does not seem to be worth the time. 

Furthermore, I'm not that fluent in Nixlang so that I got the feeling that I can deal with syntax parts that are apart, losing any tool-support for finding openening/closing brackets and so forth.

**Comment by idlip** [comment]
Ahh got it, Thank you for your reply!
